// Copyright (c) 2006 IBM. All rights reserved.

// ==================================================================
// Xen_MemorySettingData
// ==================================================================
[Provider ("cmpi:Xen_MemorySettingData"),
 Description (
        "A class derived from CIM_ResourceAllocationSettingData to "
	"represent the current and/or recorded (in snapshots/templates)"
	" settings of virtualized memory in a XenServer virtual machine.")]
class Xen_MemorySettingData : CIM_ResourceAllocationSettingData
{
};
// Copyright (c) 2006 IBM. All rights reserved.

// ==================================================================
// Xen_ProcessorSettingData
// ==================================================================
[Provider ("cmpi:Xen_ProcessorSettingData"),
 Description (
        "A class derived from CIM_ResourceAllocationSettingData to "
	"represent the current and/or recorded (in snapshots/templates) "
	"settings of a virtual processor device in a XenServer virtual machine.")]
class Xen_ProcessorSettingData : CIM_ResourceAllocationSettingData
{
};
// Copyright (c) 2006 IBM. All rights reserved.

// ==================================================================
// Xen_DiskSettingData
// ==================================================================
[Provider ("cmpi:Xen_DiskSettingData"),
 Description (
        "A class derived from CIM_StorageAllocationSettingData to "
	"represent the current and/or recorded (in snapshots/templates) "
	"settings of a virtual disk device in a XenServer virtual machine.")]
class Xen_DiskSettingData : CIM_StorageAllocationSettingData
{
    [Description ( 
          "This property specifies if the storage resource "
          "is bootable." )]
    boolean Bootable;
};

// Copyright (c) 2006 IBM. All rights reserved.

// ==================================================================
// Xen_NetworkPortSettingData
// ==================================================================
[Provider ("cmpi:Xen_NetworkPortSettingData"),
 Description (
        "A class derived from CIM_EthernetPortAllocationSettingData to "
	"represent the current and/or recorded settings (in snapshots/templates) "
	"of a virtual network interface in a XenServer virtual machine, the "
	"connection between the network interface and the network port "
	"on a virtual switch, or the network port on the virtual switch.")]
class Xen_NetworkPortSettingData : CIM_EthernetPortAllocationSettingData
{
   [Description ("VLAN Identifier for the network that this interface is attached to")]
   uint64 VlanTag;

   [Description("A boolean indicating if the MAC Address on the"
   " virtual ethernet port was randomly generated by the XenServer virtual machine.")]
   boolean AutoGeneratedMAC;
};

[Provider ("cmpi:Xen_HostNetworkPort"),
 Description (
        "A class derived from CIM_EthernetPortAllocationSettingData to represent "
        "the active and allocation settings for a network port on a XenServer Host.")]
class Xen_HostNetworkPortSettingData : CIM_EthernetPortAllocationSettingData
{
   [Description ("VLAN Identifier for the network that this network port is attached to")]
   uint64 VlanTag;

   [Description ("Name of the Xen_VirtualSwitch this network port is attached to")]
   string VirtualSwitch;

   [Description ("IP Address assigned to the network port")]
   string IPAddress;

   [ValueMap {"0","1","2","3"},
    Values {"None","DHCP","Static","Unknown"},
    Description ("IP Address configuration (None, DHCP, Static or Undefined)")]
   uint8 IPConfigurationMode;

   [Description ("Subnet Mask for the IP address")]
   string IPSubnetMask;

   [Description ("Default gateway for IP")]
   string IPGateway;

   [Description ("DNS setting for IP")]
   string DNS;

   [Description ("Indicates if this is a management NIC or not.")]
   boolean Management;

   [Description ("A user configured string indicating the purpose of this management NIC.")]
   string ManagementPurpose;
};

// ==================================================================
// Xen_ConsoleSettingData
// ==================================================================
[Provider ("cmpi:Xen_ConsoleSettingData"),
 Description (
        "A class derived from CIM_ResourceAllocationSettingData to "
	"represent the active or recorded settings of a virtualized console "
	"in a XenServer virtual machine.")]
class Xen_ConsoleSettingData : CIM_ResourceAllocationSettingData
{
   [Description ("URI for the console service")]
   string URI;

   [Description ("Display Protocol that can be used to connect to the console"),
   ValueMap { "0", "1",  "2", ".." },
   Values { "VT100", "Remote Framebuffer (VNC)", "Remote Desktop (SDL)",
      "Vendor Reserved"}]
   uint16 Protocol;
};

// ==================================================================
// Xen_KVPSettingData
// ==================================================================
[Provider ("cmpi:Xen_KVPSettingData"),
 Description (
 	     "A class derived from CIM_ResourceAllocationSettingData to "
	     "represent the key value pair records associated with a "
	     "XenServer virtual machine.")]
class Xen_KVPSettingData : CIM_ResourceAllocationSettingData
{
    [Description ("Key for the KVP record")]
    string key;
    
    [Description ("Value for the KVP record")]
    string value;

    [Description ("VM reference for the KVP record")]
    string VM_ID;
};

