del winrmtests.log
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostComputerSystem -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostPool -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualizationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MemoryCapabilitiesSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ProcessorCapabilitiesSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_StorageCapabilitiesSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkConnectionCapabilitiesSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemManagementService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
REM call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemManagementCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemMigrationService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemMigrationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemSnapshotService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemSnapshotCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSystemSnapshotServiceCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSwitchManagementService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_StoragePoolManagementService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystem -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSwitch -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostNetworkPort -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostProcessor -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostMemory -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskImage -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MemoryState -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ProcessorPool -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MemoryPool -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_StoragePool -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkConnectionPool -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_Processor -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_Memory -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_Disk -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskDrive -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkPort -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSwitchLANEndpoint -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystemLANEndpoint -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSwitchPort -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_Console -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystemSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystemTemplate -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystemSnapshot -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_VirtualSwitchSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ProcessorSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MemorySettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkPortSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostNetworkPortSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ConsoleSettingData -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MemoryAllocationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ProcessorAllocationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_StorageAllocationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkConnectionAllocationCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_MetricService -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostProcessorUtilization -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostNetworkPortReceiveThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_HostNetworkPortTransmitThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ProcessorUtilization -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskReadThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskWriteThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskReadLatency -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_DiskWriteLatency -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_ComputerSystemCapabilities -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkPortReceiveThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
call winrm enum http://schemas.citrix.com/wbem/wscim/1/cim-schema/2/Xen_NetworkPortTransmitThroughput -r:%server% -encoding:utf-8 -a:basic -u:%user% -p:%pass% >> winrmtests.log 2>&1
