// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_KVP_H__
#define __XEN_KVP_H__

/* Class Structs */

typedef struct _kvp {
  char *key;
  char *value;
  char *vm_uuid;
}kvp;

typedef struct _kvp_set {
  int size;
  kvp *contents;
}kvp_set;


/* Values for the various properties of the class */


typedef enum _Xen_KVP_AdditionalAvailability{
    Xen_KVP_AdditionalAvailability_Other=1,
    Xen_KVP_AdditionalAvailability_Unknown=2,
    Xen_KVP_AdditionalAvailability_Running_Full_Power=3,
    Xen_KVP_AdditionalAvailability_Warning=4,
    Xen_KVP_AdditionalAvailability_In_Test=5,
    Xen_KVP_AdditionalAvailability_Not_Applicable=6,
    Xen_KVP_AdditionalAvailability_Power_Off=7,
    Xen_KVP_AdditionalAvailability_Off_Line=8,
    Xen_KVP_AdditionalAvailability_Off_Duty=9,
    Xen_KVP_AdditionalAvailability_Degraded=10,
    Xen_KVP_AdditionalAvailability_Not_Installed=11,
    Xen_KVP_AdditionalAvailability_Install_Error=12,
    Xen_KVP_AdditionalAvailability_Power_Save___Unknown=13,
    Xen_KVP_AdditionalAvailability_Power_Save___Low_Power_Mode=14,
    Xen_KVP_AdditionalAvailability_Power_Save___Standby=15,
    Xen_KVP_AdditionalAvailability_Power_Cycle=16,
    Xen_KVP_AdditionalAvailability_Power_Save___Warning=17,
    Xen_KVP_AdditionalAvailability_Paused=18,
    Xen_KVP_AdditionalAvailability_Not_Ready=19,
    Xen_KVP_AdditionalAvailability_Not_Configured=20,
    Xen_KVP_AdditionalAvailability_Quiesced=21,
}Xen_KVP_AdditionalAvailability;

typedef enum _Xen_KVP_Availability{
    Xen_KVP_Availability_Other=1,
    Xen_KVP_Availability_Unknown=2,
    Xen_KVP_Availability_Running_Full_Power=3,
    Xen_KVP_Availability_Warning=4,
    Xen_KVP_Availability_In_Test=5,
    Xen_KVP_Availability_Not_Applicable=6,
    Xen_KVP_Availability_Power_Off=7,
    Xen_KVP_Availability_Off_Line=8,
    Xen_KVP_Availability_Off_Duty=9,
    Xen_KVP_Availability_Degraded=10,
    Xen_KVP_Availability_Not_Installed=11,
    Xen_KVP_Availability_Install_Error=12,
    Xen_KVP_Availability_Power_Save___Unknown=13,
    Xen_KVP_Availability_Power_Save___Low_Power_Mode=14,
    Xen_KVP_Availability_Power_Save___Standby=15,
    Xen_KVP_Availability_Power_Cycle=16,
    Xen_KVP_Availability_Power_Save___Warning=17,
    Xen_KVP_Availability_Paused=18,
    Xen_KVP_Availability_Not_Ready=19,
    Xen_KVP_Availability_Not_Configured=20,
    Xen_KVP_Availability_Quiesced=21,
}Xen_KVP_Availability;

typedef enum _Xen_KVP_AvailableRequestedStates{
    Xen_KVP_AvailableRequestedStates_Enabled=2,
    Xen_KVP_AvailableRequestedStates_Disabled=3,
    Xen_KVP_AvailableRequestedStates_Shut_Down=4,
    Xen_KVP_AvailableRequestedStates_Offline=6,
    Xen_KVP_AvailableRequestedStates_Test=7,
    Xen_KVP_AvailableRequestedStates_Defer=8,
    Xen_KVP_AvailableRequestedStates_Quiesce=9,
    Xen_KVP_AvailableRequestedStates_Reboot=10,
    Xen_KVP_AvailableRequestedStates_Reset=11,
    /*Xen_KVP_AvailableRequestedStates_DMTF_Reserved=..,*/
}Xen_KVP_AvailableRequestedStates;

typedef enum _Xen_KVP_CommunicationStatus{
    Xen_KVP_CommunicationStatus_Unknown=0,
    Xen_KVP_CommunicationStatus_Not_Available=1,
    Xen_KVP_CommunicationStatus_Communication_OK=2,
    Xen_KVP_CommunicationStatus_Lost_Communication=3,
    Xen_KVP_CommunicationStatus_No_Contact=4,
    /*Xen_KVP_CommunicationStatus_DMTF_Reserved=..,*/
    /*Xen_KVP_CommunicationStatus_Vendor_Reserved=0x8000..,*/
}Xen_KVP_CommunicationStatus;

typedef enum _Xen_KVP_DetailedStatus{
    Xen_KVP_DetailedStatus_Not_Available=0,
    Xen_KVP_DetailedStatus_No_Additional_Information=1,
    Xen_KVP_DetailedStatus_Stressed=2,
    Xen_KVP_DetailedStatus_Predictive_Failure=3,
    Xen_KVP_DetailedStatus_Non_Recoverable_Error=4,
    Xen_KVP_DetailedStatus_Supporting_Entity_in_Error=5,
    /*Xen_KVP_DetailedStatus_DMTF_Reserved=..,*/
    /*Xen_KVP_DetailedStatus_Vendor_Reserved=0x8000..,*/
}Xen_KVP_DetailedStatus;

typedef enum _Xen_KVP_EnabledDefault{
    Xen_KVP_EnabledDefault_Enabled=2,
    Xen_KVP_EnabledDefault_Disabled=3,
    Xen_KVP_EnabledDefault_Not_Applicable=5,
    Xen_KVP_EnabledDefault_Enabled_but_Offline=6,
    Xen_KVP_EnabledDefault_No_Default=7,
    Xen_KVP_EnabledDefault_Quiesce=9,
    /*Xen_KVP_EnabledDefault_DMTF_Reserved=..,*/
    /*Xen_KVP_EnabledDefault_Vendor_Reserved=32768..65535,*/
}Xen_KVP_EnabledDefault;

typedef enum _Xen_KVP_EnabledState{
    Xen_KVP_EnabledState_Unknown=0,
    Xen_KVP_EnabledState_Other=1,
    Xen_KVP_EnabledState_Enabled=2,
    Xen_KVP_EnabledState_Disabled=3,
    Xen_KVP_EnabledState_Shutting_Down=4,
    Xen_KVP_EnabledState_Not_Applicable=5,
    Xen_KVP_EnabledState_Enabled_but_Offline=6,
    Xen_KVP_EnabledState_In_Test=7,
    Xen_KVP_EnabledState_Deferred=8,
    Xen_KVP_EnabledState_Quiesce=9,
    Xen_KVP_EnabledState_Starting=10,
    /*Xen_KVP_EnabledState_DMTF_Reserved=11..32767,*/
    /*Xen_KVP_EnabledState_Vendor_Reserved=32768..65535,*/
}Xen_KVP_EnabledState;

typedef enum _Xen_KVP_HealthState{
    Xen_KVP_HealthState_Unknown=0,
    Xen_KVP_HealthState_OK=5,
    Xen_KVP_HealthState_Degraded_Warning=10,
    Xen_KVP_HealthState_Minor_failure=15,
    Xen_KVP_HealthState_Major_failure=20,
    Xen_KVP_HealthState_Critical_failure=25,
    Xen_KVP_HealthState_Non_recoverable_error=30,
    /*Xen_KVP_HealthState_DMTF_Reserved=..,*/
}Xen_KVP_HealthState;

typedef enum _Xen_KVP_LocationIndicator{
    Xen_KVP_LocationIndicator_Unknown=0,
    Xen_KVP_LocationIndicator_On=2,
    Xen_KVP_LocationIndicator_Off=3,
    Xen_KVP_LocationIndicator_Not_Supported=4,
}Xen_KVP_LocationIndicator;

typedef enum _Xen_KVP_OperatingStatus{
    Xen_KVP_OperatingStatus_Unknown=0,
    Xen_KVP_OperatingStatus_Not_Available=1,
    Xen_KVP_OperatingStatus_Servicing=2,
    Xen_KVP_OperatingStatus_Starting=3,
    Xen_KVP_OperatingStatus_Stopping=4,
    Xen_KVP_OperatingStatus_Stopped=5,
    Xen_KVP_OperatingStatus_Aborted=6,
    Xen_KVP_OperatingStatus_Dormant=7,
    Xen_KVP_OperatingStatus_Completed=8,
    Xen_KVP_OperatingStatus_Migrating=9,
    Xen_KVP_OperatingStatus_Emigrating=10,
    Xen_KVP_OperatingStatus_Immigrating=11,
    Xen_KVP_OperatingStatus_Snapshotting=12,
    Xen_KVP_OperatingStatus_Shutting_Down=13,
    Xen_KVP_OperatingStatus_In_Test=14,
    Xen_KVP_OperatingStatus_Transitioning=15,
    Xen_KVP_OperatingStatus_In_Service=16,
    /*Xen_KVP_OperatingStatus_DMTF_Reserved=..,*/
    /*Xen_KVP_OperatingStatus_Vendor_Reserved=0x8000..,*/
}Xen_KVP_OperatingStatus;

typedef enum _Xen_KVP_OperationalStatus{
    Xen_KVP_OperationalStatus_Unknown=0,
    Xen_KVP_OperationalStatus_Other=1,
    Xen_KVP_OperationalStatus_OK=2,
    Xen_KVP_OperationalStatus_Degraded=3,
    Xen_KVP_OperationalStatus_Stressed=4,
    Xen_KVP_OperationalStatus_Predictive_Failure=5,
    Xen_KVP_OperationalStatus_Error=6,
    Xen_KVP_OperationalStatus_Non_Recoverable_Error=7,
    Xen_KVP_OperationalStatus_Starting=8,
    Xen_KVP_OperationalStatus_Stopping=9,
    Xen_KVP_OperationalStatus_Stopped=10,
    Xen_KVP_OperationalStatus_In_Service=11,
    Xen_KVP_OperationalStatus_No_Contact=12,
    Xen_KVP_OperationalStatus_Lost_Communication=13,
    Xen_KVP_OperationalStatus_Aborted=14,
    Xen_KVP_OperationalStatus_Dormant=15,
    Xen_KVP_OperationalStatus_Supporting_Entity_in_Error=16,
    Xen_KVP_OperationalStatus_Completed=17,
    Xen_KVP_OperationalStatus_Power_Mode=18,
    /*Xen_KVP_OperationalStatus_DMTF_Reserved=..,*/
    /*Xen_KVP_OperationalStatus_Vendor_Reserved=0x8000..,*/
}Xen_KVP_OperationalStatus;

typedef enum _Xen_KVP_PowerManagementCapabilities{
    Xen_KVP_PowerManagementCapabilities_Unknown=0,
    Xen_KVP_PowerManagementCapabilities_Not_Supported=1,
    Xen_KVP_PowerManagementCapabilities_Disabled=2,
    Xen_KVP_PowerManagementCapabilities_Enabled=3,
    Xen_KVP_PowerManagementCapabilities_Power_Saving_Modes_Entered_Automatically=4,
    Xen_KVP_PowerManagementCapabilities_Power_State_Settable=5,
    Xen_KVP_PowerManagementCapabilities_Power_Cycling_Supported=6,
    Xen_KVP_PowerManagementCapabilities_Timed_Power_On_Supported=7,
}Xen_KVP_PowerManagementCapabilities;

typedef enum _Xen_KVP_PrimaryStatus{
    Xen_KVP_PrimaryStatus_Unknown=0,
    Xen_KVP_PrimaryStatus_OK=1,
    Xen_KVP_PrimaryStatus_Degraded=2,
    Xen_KVP_PrimaryStatus_Error=3,
    /*Xen_KVP_PrimaryStatus_DMTF_Reserved=..,*/
    /*Xen_KVP_PrimaryStatus_Vendor_Reserved=0x8000..,*/
}Xen_KVP_PrimaryStatus;

typedef enum _Xen_KVP_RequestedState{
    Xen_KVP_RequestedState_Unknown=0,
    Xen_KVP_RequestedState_Enabled=2,
    Xen_KVP_RequestedState_Disabled=3,
    Xen_KVP_RequestedState_Shut_Down=4,
    Xen_KVP_RequestedState_No_Change=5,
    Xen_KVP_RequestedState_Offline=6,
    Xen_KVP_RequestedState_Test=7,
    Xen_KVP_RequestedState_Deferred=8,
    Xen_KVP_RequestedState_Quiesce=9,
    Xen_KVP_RequestedState_Reboot=10,
    Xen_KVP_RequestedState_Reset=11,
    Xen_KVP_RequestedState_Not_Applicable=12,
    /*Xen_KVP_RequestedState_DMTF_Reserved=..,*/
    /*Xen_KVP_RequestedState_Vendor_Reserved=32768..65535,*/
}Xen_KVP_RequestedState;

#define Xen_KVP_Status_OK "OK"
#define Xen_KVP_Status_Error "Error"
#define Xen_KVP_Status_Degraded "Degraded"
#define Xen_KVP_Status_Unknown "Unknown"
#define Xen_KVP_Status_Pred_Fail "Pred Fail"
#define Xen_KVP_Status_Starting "Starting"
#define Xen_KVP_Status_Stopping "Stopping"
#define Xen_KVP_Status_Service "Service"
#define Xen_KVP_Status_Stressed "Stressed"
#define Xen_KVP_Status_NonRecover "NonRecover"
#define Xen_KVP_Status_No_Contact "No Contact"
#define Xen_KVP_Status_Lost_Comm "Lost Comm"
#define Xen_KVP_Status_Stopped "Stopped"

typedef enum _Xen_KVP_ReturnCode{
    Xen_KVP_RC_OK=0,
    Xen_KVP_RC_ERROR=1,
    Xen_KVP_RC_FAILED=2,
    Xen_KVP_RC_HOST_UNKOWN=3,
} Xen_KVP_RC;


typedef enum _Xen_KVP_StatusInfo{
    Xen_KVP_StatusInfo_Other=1,
    Xen_KVP_StatusInfo_Unknown=2,
    Xen_KVP_StatusInfo_Enabled=3,
    Xen_KVP_StatusInfo_Disabled=4,
    Xen_KVP_StatusInfo_Not_Applicable=5,
}Xen_KVP_StatusInfo;

typedef enum _Xen_KVP_TransitioningToState{
    Xen_KVP_TransitioningToState_Unknown=0,
    Xen_KVP_TransitioningToState_Enabled=2,
    Xen_KVP_TransitioningToState_Disabled=3,
    Xen_KVP_TransitioningToState_Shut_Down=4,
    Xen_KVP_TransitioningToState_No_Change=5,
    Xen_KVP_TransitioningToState_Offline=6,
    Xen_KVP_TransitioningToState_Test=7,
    Xen_KVP_TransitioningToState_Defer=8,
    Xen_KVP_TransitioningToState_Quiesce=9,
    Xen_KVP_TransitioningToState_Reboot=10,
    Xen_KVP_TransitioningToState_Reset=11,
    Xen_KVP_TransitioningToState_Not_Applicable=12,
    /*Xen_KVP_TransitioningToState_DMTF_Reserved=..,*/
}Xen_KVP_TransitioningToState;

typedef enum _Xen_KVP_RequestStateChange{
    Xen_KVP_RequestStateChange_Completed_with_No_Error=0,
    Xen_KVP_RequestStateChange_Not_Supported=1,
    Xen_KVP_RequestStateChange_Unknown_or_Unspecified_Error=2,
    Xen_KVP_RequestStateChange_Cannot_complete_within_Timeout_Period=3,
    Xen_KVP_RequestStateChange_Failed=4,
    Xen_KVP_RequestStateChange_Invalid_Parameter=5,
    Xen_KVP_RequestStateChange_In_Use=6,
    /*Xen_KVP_RequestStateChange_DMTF_Reserved=..,*/
    Xen_KVP_RequestStateChange_Method_Parameters_Checked___Job_Started=4096,
    Xen_KVP_RequestStateChange_Invalid_State_Transition=4097,
    Xen_KVP_RequestStateChange_Use_of_Timeout_Parameter_Not_Supported=4098,
    Xen_KVP_RequestStateChange_Busy=4099,
    /*Xen_KVP_RequestStateChange_Method_Reserved=4100..32767,*/
    /*Xen_KVP_RequestStateChange_Vendor_Specific=32768..65535,*/
}Xen_KVP_RequestStateChange;

#endif /*__XEN_KVP_H__*/
