// Copyright (C) 2006 IBM Corporation
//
//    This library is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Lesser General Public
//    License as published by the Free Software Foundation; either
//    version 2.1 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Lesser General Public License for more details.
//
//    You should have received a copy of the GNU Lesser General Public
//    License along with this library; if not, write to the Free Software
//    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

/******************************************************************************
 * These enums were generated by the codegen script from the MOF declarations
 *****************************************************************************/
/* Values for the various properties of the class */

/******************************************************************************
 * Virtual System Management Service Capabilities
 *****************************************************************************/
typedef enum {
   AddResourcesSupported = 1,
   DefineSystemSupported,
   DestroySystemSupported,
   DestroySystemConfigurationSupported,
   ModifyResourceSettingsSupported,
   ModifySystemSettingsSupported,
   RemoveResourcesSupported,
   SelectSystemConfigurationSupported,
   SnapshotSystemSupported,
   AddResourceSupported
}VSMSSupportedType;

typedef enum {
    VirtualSystemStateChangeIndicationsSupported = 1, 
    VirtualResourceStateChangeIndicationsSupported, 
    ConcreteJobStateChangeIndicationsSupported
}VSMSIndicationType;

typedef struct {
    char *MethodName;
    VSMSSupportedType supportedType;
} VSMSMethodSupported;

/******************************************************************************
 * Virtual System Snapshot Capabilities - supported by xen
 *****************************************************************************/
typedef enum _Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled{
    Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled_Full_Snapshot=2,
    Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled_Disk_Snapshot=3,
    /*Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled_DMTF_Reserved=..,*/
    /*Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled_Vendor_Specific=32768..65535,*/
}Xen_VirtualSystemSnapshotCapabilities_SnapshotTypesEnabled;

/******************************************************************************
 * Virtual System Snapshot Service Capabilities
 *****************************************************************************/
typedef enum _Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported{
    Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported_CreateSnapshotSupported=2,
    Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported_DestroySnapshotSupported=3,
    Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported_ApplySnapshotSupported=4,
    /*Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported_DMTF_Reserved=..,*/
}Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported;

Xen_VirtualSystemSnapshotServiceCapabilities_AynchronousMethodsSupported g_SnapSvcAsynchronousMethodsSupported[] = {
};

typedef enum _Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported{
    Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported_Full_Snapshot=2,
    Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported_Disk_Snapshot=3,
    /*Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported_DMTF_Reserved=..,*/
    /*Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported_Vendor_Specific=32768..65535,*/
}Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported;

Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported g_SnapSvcSnapshotTypesSupported[] = {
    Xen_VirtualSystemSnapshotServiceCapabilities_SnapshotTypesSupported_Full_Snapshot
};

typedef enum _Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported{
    Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_CreateSnapshotSupported=2,
    Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_DestroySnapshotSupported=3,
    Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_ApplySnapshotSupported=4,
    /*Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_DMTF_Reserved=..,*/
}Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported;

Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported g_SnapSvcSynchronousMethodsSupported[] = {
    Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_CreateSnapshotSupported,
    Xen_VirtualSystemSnapshotServiceCapabilities_SynchronousMethodsSupported_DestroySnapshotSupported
};

/******************************************************************************
 * Virtual System Migration Service Capabilities
 *****************************************************************************/
typedef enum _Xen_VirtualSystemMigrationCapabilities_AsynchronousMethodsSupported{
    Xen_VirtualSystemMigrationCapabilities_AsynchronousMethodsSupported_MigrateVirtualSystemToHostSupported=2,
    Xen_VirtualSystemMigrationCapabilities_AsynchronousMethodsSupported_MigrateVirtualSystemToSystemSupported=3,
    /*Xen_VirtualSystemMigrationCapabilities_AsynchronousMethodsSupported_DMTF_Reserved=..,*/
}Xen_VirtualSystemMigrationCapabilities_AsynchronousMethodsSupported;

typedef enum _Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported{
    Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported_DomainNameFormatSupported=2,
    Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported_IPv4DottedDecimalFormatSupported=3,
    Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported_IPv6TextFormatSupported=4,
    /*Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported_DMTF_Reserved=..,*/
}Xen_VirtualSystemMigrationCapabilities_DestinationHostFormatsSupported;

typedef enum _Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported{
    Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported_MigrateVirtualSystemToHostSupported=2,
    Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported_MigrateVirtualSystemToSystemSupported=3,
    Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported_CheckVirtualSystemIsMigratableToHostSupported=4,
    Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported_CheckVirtualSystemIsMigratableToSystemSupported=5,
    /*Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported_DMTF_Reserved=..,*/
}Xen_VirtualSystemMigrationCapabilities_SynchronousMethodsSupported;

