// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_COMPUTERSYSTEM_H__
#define __XEN_COMPUTERSYSTEM_H__
#include <xen/api/xen_vm_operations.h>
/* Values for the various properties of the class */
typedef enum _VM_RequestStateChange{
    VM_RequestStateChange_Completed_with_No_Error=0,
    VM_RequestStateChange_Not_Supported=1,
    VM_RequestStateChange_Unknown_or_Unspecified_Error=2,
    VM_RequestStateChange_Cannot_complete_within_Timeout_Period=3,
    VM_RequestStateChange_Failed=4,
    VM_RequestStateChange_Invalid_Parameter=5,
    VM_RequestStateChange_In_Use=6,
    /*VM_RequestStateChange_DMTF_Reserved=..,*/
    VM_RequestStateChange_Method_Parameters_Checked___Job_Started=4096,
    VM_RequestStateChange_Invalid_State_Transition=4097,
    VM_RequestStateChange_Use_of_Timeout_Parameter_Not_Supported=4098,
    VM_RequestStateChange_Busy=4099,
    /*VM_RequestStateChange_Method_Reserved=4100..32767,*/
    /*VM_RequestStateChange_Vendor_Specific=32768..65535,*/
}VM_RequestStateChange;

typedef enum _VM_RequestedState{
    VM_RequestedState_Unknown=0,
    VM_RequestedState_Enabled=2,
    VM_RequestedState_Disabled=3,
    VM_RequestedState_Shut_Down=4,
    VM_RequestedState_No_Change=5,
    VM_RequestedState_Offline=6,
    VM_RequestedState_Test=7,
    VM_RequestedState_Deferred=8,
    VM_RequestedState_Quiesce=9,
    VM_RequestedState_Reboot=10,
    VM_RequestedState_Reset=11,
    VM_RequestedState_Not_Applicable=12,
    /*VM_RequestedState_VM_Reserved=..,*/
    VM_RequestedState_HardShutdown=32768,
    VM_RequestedState_HardReboot=32769
    /*VM_RequestedState_Vendor_Reserved=32768..65535,*/
}VM_RequestedState;

struct RequestedStateMap {
    VM_RequestedState dmtf_val;
    enum xen_vm_operations xen_val;
};

#endif /*__XEN_COMPUTERSYSTEM_H__*/
