// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_VIRTUALSWITCHMANAGEMENTSERVICE_H__
#define __XEN_VIRTUALSWITCHMANAGEMENTSERVICE_H__

/* Values for the various properties of the class's methods */
typedef enum _Xen_VirtualSwitchManagementService_RequestStateChange{
    Xen_VirtualSwitchManagementService_RequestStateChange_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_RequestStateChange_Not_Supported=1,
    Xen_VirtualSwitchManagementService_RequestStateChange_Unknown_or_Unspecified_Error=2,
    Xen_VirtualSwitchManagementService_RequestStateChange_Cannot_complete_within_Timeout_Period=3,
    Xen_VirtualSwitchManagementService_RequestStateChange_Failed=4,
    Xen_VirtualSwitchManagementService_RequestStateChange_Invalid_Parameter=5,
    Xen_VirtualSwitchManagementService_RequestStateChange_In_Use=6,
    /*Xen_VirtualSwitchManagementService_RequestStateChange_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_RequestStateChange_Method_Parameters_Checked___Job_Started=4096,
    Xen_VirtualSwitchManagementService_RequestStateChange_Invalid_State_Transition=4097,
    Xen_VirtualSwitchManagementService_RequestStateChange_Use_of_Timeout_Parameter_Not_Supported=4098,
    Xen_VirtualSwitchManagementService_RequestStateChange_Busy=4099,
    /*Xen_VirtualSwitchManagementService_RequestStateChange_Method_Reserved=4100..32767,*/
    /*Xen_VirtualSwitchManagementService_RequestStateChange_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_RequestStateChange;

typedef enum _Xen_VirtualSwitchManagementService_AddResourceSettings{
    Xen_VirtualSwitchManagementService_AddResourceSettings_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_AddResourceSettings_Not_Supported=1,
    Xen_VirtualSwitchManagementService_AddResourceSettings_Failed=2,
    Xen_VirtualSwitchManagementService_AddResourceSettings_Timeout=3,
    Xen_VirtualSwitchManagementService_AddResourceSettings_Invalid_Parameter=4,
    /*Xen_VirtualSwitchManagementService_AddResourceSettings_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_AddResourceSettings_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_AddResourceSettings_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_AddResourceSettings_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_AddResourceSettings;

typedef enum _Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence{
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Not_Supported=1,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Error_Occured=2,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Busy=3,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Invalid_Reference=4,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Invalid_Parameter=5,
    Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Access_Denied=6,
    /*Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_DMTF_Reserved=7..32767,*/
    /*Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence_Vendor_Specified=32768..65535,*/
}Xen_VirtualSwitchManagementService_ChangeAffectedElementsAssignedSequence;

typedef enum _Xen_VirtualSwitchManagementService_DefineSystem{
    Xen_VirtualSwitchManagementService_DefineSystem_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_DefineSystem_Not_Supported=1,
    Xen_VirtualSwitchManagementService_DefineSystem_Failed=2,
    Xen_VirtualSwitchManagementService_DefineSystem_Timeout=3,
    Xen_VirtualSwitchManagementService_DefineSystem_Invalid_Parameter=4,
    /*Xen_VirtualSwitchManagementService_DefineSystem_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_DefineSystem_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_DefineSystem_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_DefineSystem_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_DefineSystem;

typedef enum _Xen_VirtualSwitchManagementService_DestroySystem{
    Xen_VirtualSwitchManagementService_DestroySystem_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_DestroySystem_Not_Supported=1,
    Xen_VirtualSwitchManagementService_DestroySystem_Failed=2,
    Xen_VirtualSwitchManagementService_DestroySystem_Timeout=3,
    Xen_VirtualSwitchManagementService_DestroySystem_Invalid_Parameter=4,
    Xen_VirtualSwitchManagementService_DestroySystem_Invalid_State=5,
    /*Xen_VirtualSwitchManagementService_DestroySystem_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_DestroySystem_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_DestroySystem_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_DestroySystem_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_DestroySystem;

typedef enum _Xen_VirtualSwitchManagementService_RemoveResourceSettings{
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Not_Supported=1,
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Failed=2,
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Timeout=3,
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Invalid_Parameter=4,
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Invalid_State=5,
    /*Xen_VirtualSwitchManagementService_RemoveResourceSettings_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_RemoveResourceSettings_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_RemoveResourceSettings_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_RemoveResourceSettings_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_RemoveResourceSettings;

typedef enum _Xen_VirtualSwitchManagementService_ModifySystemSettings{
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Not_Supported=1,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Failed=2,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Timeout=3,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Invalid_Parameter=4,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Invalid_State=5,
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Incompatible_Parameters=6,
    /*Xen_VirtualSwitchManagementService_ModifySystemSettings_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_ModifySystemSettings_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_ModifySystemSettings_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_ModifySystemSettings_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_ModifySystemSettings;

typedef enum _Xen_VirtualSwitchManagementService_ModifyResourceSettings{
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Completed_with_No_Error=0,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Not_Supported=1,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Failed=2,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Timeout=3,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Invalid_Parameter=4,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Invalid_State=5,
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Incompatible_Parameters=6,
    /*Xen_VirtualSwitchManagementService_ModifyResourceSettings_DMTF_Reserved=..,*/
    Xen_VirtualSwitchManagementService_ModifyResourceSettings_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_VirtualSwitchManagementService_ModifyResourceSettings_Method_Reserved=4097..32767,*/
    /*Xen_VirtualSwitchManagementService_ModifyResourceSettings_Vendor_Specific=32768..65535,*/
}Xen_VirtualSwitchManagementService_ModifyResourceSettings;


#endif /*__XEN_VIRTUALSWITCHMANAGEMENTSERVICE_H__*/
