// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_CONSOLE_H__
#define __XEN_CONSOLE_H__

/* Values for the various properties of the class */
typedef enum _Xen_Console_Logout{
    Xen_Console_Logout_Completed_with_No_Error=0,
    Xen_Console_Logout_Not_Supported=1,
    Xen_Console_Logout_Failed=2,
    Xen_Console_Logout_Timeout=3,
    Xen_Console_Logout_Invalid_Parameter=4,
    /*Xen_Console_Logout_DMTF_Reserved=..,*/
    Xen_Console_Logout_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_Console_Logout_Method_Reserved=4097..32767,*/
    /*Xen_Console_Logout_Vendor_Specific=32768..65535,*/
}Xen_Console_Logout;

typedef enum _Xen_Console_Login{
    Xen_Console_Login_Completed_with_No_Error=0,
    Xen_Console_Login_Not_Supported=1,
    Xen_Console_Login_Failed=2,
    Xen_Console_Login_Timeout=3,
    Xen_Console_Login_Invalid_Parameter=4,
    /*Xen_Console_Login_DMTF_Reserved=..,*/
    Xen_Console_Login_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_Console_Login_Method_Reserved=4097..32767,*/
    /*Xen_Console_Login_Vendor_Specific=32768..65535,*/
}Xen_Console_Login;


#endif /*__XEN_CONSOLE_H__*/
