// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_METRICSERVICE_H__
#define __XEN_METRICSERVICE_H__

/* Values for the various properties of the class */
typedef enum _Xen_MetricService_ShowMetrics{
    Xen_MetricService_ShowMetrics_Success=0,
    Xen_MetricService_ShowMetrics_Not_Supported=1,
    Xen_MetricService_ShowMetrics_Failed=2,
    /*Xen_MetricService_ShowMetrics_Method_Reserved=..,*/
    /*Xen_MetricService_ShowMetrics_Vendor_Specific=32768..65535,*/
}Xen_MetricService_ShowMetrics;

typedef enum _Xen_MetricService_ChangeAffectedElementsAssignedSequence{
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Completed_with_No_Error=0,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Not_Supported=1,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Error_Occured=2,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Busy=3,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Invalid_Reference=4,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Invalid_Parameter=5,
    Xen_MetricService_ChangeAffectedElementsAssignedSequence_Access_Denied=6,
    /*Xen_MetricService_ChangeAffectedElementsAssignedSequence_DMTF_Reserved=7..32767,*/
    /*Xen_MetricService_ChangeAffectedElementsAssignedSequence_Vendor_Specified=32768..65535,*/
}Xen_MetricService_ChangeAffectedElementsAssignedSequence;

typedef enum _Xen_MetricService_ControlMetrics{
    Xen_MetricService_ControlMetrics_Success=0,
    Xen_MetricService_ControlMetrics_Not_Supported=1,
    Xen_MetricService_ControlMetrics_Failed=2,
    /*Xen_MetricService_ControlMetrics_Method_Reserved=..,*/
    /*Xen_MetricService_ControlMetrics_Vendor_Specific=32768..65535,*/
}Xen_MetricService_ControlMetrics;

typedef enum _Xen_MetricService_GetMetricValues{
    Xen_MetricService_GetMetricValues_Success=0,
    Xen_MetricService_GetMetricValues_Not_Supported=1,
    Xen_MetricService_GetMetricValues_Failed=2,
    /*Xen_MetricService_GetMetricValues_Method_Reserved=..,*/
    /*Xen_MetricService_GetMetricValues_Vendor_Specific=32768..65535,*/
}Xen_MetricService_GetMetricValues;

typedef enum _Xen_MetricService_GetPerformanceMetricsForSystem{
    Xen_MetricService_GetPerformanceMetricsForSystem_Completed_with_No_Error=0,
    Xen_MetricService_GetPerformanceMetricsForSystem_Not_Supported=1,
    Xen_MetricService_GetPerformanceMetricsForSystem_Failed=2,
    Xen_MetricService_GetPerformanceMetricsForSystem_Timeout=3,
    Xen_MetricService_GetPerformanceMetricsForSystem_Invalid_Parameter=4,
    /*Xen_MetricService_GetPerformanceMetricsForSystem_DMTF_Reserved=..,*/
    Xen_MetricService_GetPerformanceMetricsForSystem_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_MetricService_GetPerformanceMetricsForSystem_Method_Reserved=4097..32767,*/
    /*Xen_MetricService_GetPerformanceMetricsForSystem_Vendor_Specific=32768..65535,*/
}Xen_MetricService_GetPerformanceMetricsForSystem;

typedef enum _Xen_MetricService_ControlMetricsByClass{
    Xen_MetricService_ControlMetricsByClass_Success=0,
    Xen_MetricService_ControlMetricsByClass_Not_Supported=1,
    Xen_MetricService_ControlMetricsByClass_Failed=2,
    /*Xen_MetricService_ControlMetricsByClass_Method_Reserved=..,*/
    /*Xen_MetricService_ControlMetricsByClass_Vendor_Specific=32768..65535,*/
}Xen_MetricService_ControlMetricsByClass;

typedef enum _Xen_MetricService_ShowMetricsByClass{
    Xen_MetricService_ShowMetricsByClass_Success=0,
    Xen_MetricService_ShowMetricsByClass_Not_Supported=1,
    Xen_MetricService_ShowMetricsByClass_Failed=2,
    /*Xen_MetricService_ShowMetricsByClass_Method_Reserved=..,*/
    /*Xen_MetricService_ShowMetricsByClass_Vendor_Specific=32768..65535,*/
}Xen_MetricService_ShowMetricsByClass;


#endif /*__XEN_METRICSERVICE_H__*/
