// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_DISK_H__
#define __XEN_DISK_H__

/* Values for the various properties of the class */
typedef enum _Access{
    Access_Unknown=0,
    Access_Readable=1,
    Access_Writeable=2,
    Access_Read_Write_Supported=3,
    Access_Write_Once=4,
}Access;

typedef enum _DataOrganization{
    DataOrganization_Other=0,
    DataOrganization_Unknown=1,
    DataOrganization_Fixed_Block=2,
    DataOrganization_Variable_Block=3,
    DataOrganization_Count_Key_Data=4,
}DataOrganization;

typedef enum _ExtentStatus{
    ExtentStatus_Other=0,
    ExtentStatus_Unknown=1,
    ExtentStatus_None_Not_Applicable=2,
    ExtentStatus_Broken=3,
    ExtentStatus_Data_Lost=4,
    ExtentStatus_Dynamic_Reconfig=5,
    ExtentStatus_Exposed=6,
    ExtentStatus_Fractionally_Exposed=7,
    ExtentStatus_Partially_Exposed=8,
    ExtentStatus_Protection_Disabled=9,
    ExtentStatus_Readying=10,
    ExtentStatus_Rebuild=11,
    ExtentStatus_Recalculate=12,
    ExtentStatus_Spare_in_Use=13,
    ExtentStatus_Verify_In_Progress=14,
    ExtentStatus_In_Band_Access_Granted=15,
    ExtentStatus_Imported=16,
    ExtentStatus_Exported=17,
    /*ExtentStatus_DMTF_Reserved=18..32767,*/
    /*ExtentStatus_Vendor_Reserved=32768..65535,*/
}ExtentStatus;

typedef enum _NameFormat{
    NameFormat_Unknown=0,
    NameFormat_Other=1,
    NameFormat_VPD83NAA6=2,
    NameFormat_VPD83NAA5=3,
    NameFormat_VPD83Type2=4,
    NameFormat_VPD83Type1=5,
    NameFormat_VPD83Type0=6,
    NameFormat_SNVM=7,
    NameFormat_NodeWWN=8,
    NameFormat_NAA=9,
    NameFormat_EUI64=10,
    NameFormat_T10VID=11,
    NameFormat_OS_Device_Name=12,
}NameFormat;

typedef enum _NameNamespace{
    NameNamespace_Unknown=0,
    NameNamespace_Other=1,
    NameNamespace_VPD83Type3=2,
    NameNamespace_VPD83Type2=3,
    NameNamespace_VPD83Type1=4,
    NameNamespace_VPD80=5,
    NameNamespace_NodeWWN=6,
    NameNamespace_SNVM=7,
    NameNamespace_OS_Device_Namespace=8,
}NameNamespace;

typedef enum _PowerManagementCapabilities{
    PowerManagementCapabilities_Unknown=0,
    PowerManagementCapabilities_Not_Supported=1,
    PowerManagementCapabilities_Disabled=2,
    PowerManagementCapabilities_Enabled=3,
    PowerManagementCapabilities_Power_Saving_Modes_Entered_Automatically=4,
    PowerManagementCapabilities_Power_State_Settable=5,
    PowerManagementCapabilities_Power_Cycling_Supported=6,
    PowerManagementCapabilities_Timed_Power_On_Supported=7,
}PowerManagementCapabilities;

#endif /*__XEN_DISK_H__*/
