// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_KVPSETTINGDATA_H__
#define __XEN_KVPSETTINGDATA_H__

/* Values for the various properties of the class */


typedef enum _Xen_KVPSettingData_ChangeableType{
    Xen_KVPSettingData_ChangeableType_Not_Changeable___Persistent=0,
    Xen_KVPSettingData_ChangeableType_Changeable___Transient=1,
    Xen_KVPSettingData_ChangeableType_Changeable___Persistent=2,
    Xen_KVPSettingData_ChangeableType_Not_Changeable___Transient=3,
}Xen_KVPSettingData_ChangeableType;

typedef enum _Xen_KVPSettingData_ConsumerVisibility{
    Xen_KVPSettingData_ConsumerVisibility_Unknown=0,
    Xen_KVPSettingData_ConsumerVisibility_Passed_Through=2,
    Xen_KVPSettingData_ConsumerVisibility_Virtualized=3,
    Xen_KVPSettingData_ConsumerVisibility_Not_represented=4,
    /*Xen_KVPSettingData_ConsumerVisibility_DMTF_reserved=..,*/
    /*Xen_KVPSettingData_ConsumerVisibility_Vendor_Reserved=32767..65535,*/
}Xen_KVPSettingData_ConsumerVisibility;

typedef enum _Xen_KVPSettingData_MappingBehavior{
    Xen_KVPSettingData_MappingBehavior_Unknown=0,
    Xen_KVPSettingData_MappingBehavior_Not_Supported=2,
    Xen_KVPSettingData_MappingBehavior_Dedicated=3,
    Xen_KVPSettingData_MappingBehavior_Soft_Affinity=4,
    Xen_KVPSettingData_MappingBehavior_Hard_Affinity=5,
    /*Xen_KVPSettingData_MappingBehavior_DMTF_Reserved=..,*/
    /*Xen_KVPSettingData_MappingBehavior_Vendor_Reserved=32767..65535,*/
}Xen_KVPSettingData_MappingBehavior;

typedef enum _Xen_KVPSettingData_ResourceType{
    Xen_KVPSettingData_ResourceType_Other=1,
    Xen_KVPSettingData_ResourceType_Computer_System=2,
    Xen_KVPSettingData_ResourceType_Processor=3,
    Xen_KVPSettingData_ResourceType_Memory=4,
    Xen_KVPSettingData_ResourceType_IDE_Controller=5,
    Xen_KVPSettingData_ResourceType_Parallel_SCSI_HBA=6,
    Xen_KVPSettingData_ResourceType_FC_HBA=7,
    Xen_KVPSettingData_ResourceType_iSCSI_HBA=8,
    Xen_KVPSettingData_ResourceType_IB_HCA=9,
    Xen_KVPSettingData_ResourceType_Ethernet_Adapter=10,
    Xen_KVPSettingData_ResourceType_Other_Network_Adapter=11,
    Xen_KVPSettingData_ResourceType_I_O_Slot=12,
    Xen_KVPSettingData_ResourceType_I_O_Device=13,
    Xen_KVPSettingData_ResourceType_Floppy_Drive=14,
    Xen_KVPSettingData_ResourceType_CD_Drive=15,
    Xen_KVPSettingData_ResourceType_DVD_drive=16,
    Xen_KVPSettingData_ResourceType_Disk_Drive=17,
    Xen_KVPSettingData_ResourceType_Tape_Drive=18,
    Xen_KVPSettingData_ResourceType_Storage_Extent=19,
    Xen_KVPSettingData_ResourceType_Other_storage_device=20,
    Xen_KVPSettingData_ResourceType_Serial_port=21,
    Xen_KVPSettingData_ResourceType_Parallel_port=22,
    Xen_KVPSettingData_ResourceType_USB_Controller=23,
    Xen_KVPSettingData_ResourceType_Graphics_controller=24,
    Xen_KVPSettingData_ResourceType_IEEE_1394_Controller=25,
    Xen_KVPSettingData_ResourceType_Partitionable_Unit=26,
    Xen_KVPSettingData_ResourceType_Base_Partitionable_Unit=27,
    Xen_KVPSettingData_ResourceType_Power=28,
    Xen_KVPSettingData_ResourceType_Cooling_Capacity=29,
    Xen_KVPSettingData_ResourceType_Ethernet_Switch_Port=30,
    Xen_KVPSettingData_ResourceType_Logical_Disk=31,
    Xen_KVPSettingData_ResourceType_Storage_Volume=32,
    Xen_KVPSettingData_ResourceType_Ethernet_Connection=33,
    /*Xen_KVPSettingData_ResourceType_DMTF_reserved=..,*/
    /*Xen_KVPSettingData_ResourceType_Vendor_Reserved=0x8000..0xFFFF,*/
}Xen_KVPSettingData_ResourceType;


#endif /*__XEN_KVPSETTINGDATA_H__*/
