// ***** Generated by Codegen *****
// Copyright (C) 2008-2009 Citrix Systems Inc
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

#ifndef __XEN_STORAGEPOOLMANAGEMENTSERVICE_H__
#define __XEN_STORAGEPOOLMANAGEMENTSERVICE_H__

/* Values for the various properties of the class */
typedef enum _Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence{
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Not_Supported=1,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Error_Occured=2,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Busy=3,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Invalid_Reference=4,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Access_Denied=6,
    /*Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_DMTF_Reserved=7..32767,*/
    /*Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence_Vendor_Specified=32768..65535,*/
}Xen_StoragePoolManagementService_ChangeAffectedElementsAssignedSequence;

typedef enum _Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool{
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Failed=4,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    /*Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Method_Parameters_Checked___Job_Started=4096,
    Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Size_Not_Supported=4097,
    /*Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Method_Reserved=4098..32767,*/
    /*Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_RemoveResourcesFromResourcePool;

typedef enum _Xen_StoragePoolManagementService_ConnectToDiskImages{
    Xen_StoragePoolManagementService_ConnectToDiskImages_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_ConnectToDiskImages_Not_Supported=1,
    Xen_StoragePoolManagementService_ConnectToDiskImages_Failed=2,
    Xen_StoragePoolManagementService_ConnectToDiskImages_Timeout=3,
    Xen_StoragePoolManagementService_ConnectToDiskImages_Invalid_Parameter=4,
    /*Xen_StoragePoolManagementService_ConnectToDiskImages_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_ConnectToDiskImages_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_StoragePoolManagementService_ConnectToDiskImages_Method_Reserved=4097..32767,*/
    /*Xen_StoragePoolManagementService_ConnectToDiskImages_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_ConnectToDiskImages;

typedef enum _Xen_StoragePoolManagementService_ChangeParentResourcePool{
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Failed=4,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Insufficient_Resources=8,
    /*Xen_StoragePoolManagementService_ChangeParentResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Method_Parameters_Checked___Job_Started=4096,
    Xen_StoragePoolManagementService_ChangeParentResourcePool_Size_Not_Supported=4097,
    /*Xen_StoragePoolManagementService_ChangeParentResourcePool_Method_Reserved=4098..32767,*/
    /*Xen_StoragePoolManagementService_ChangeParentResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_ChangeParentResourcePool;

typedef enum _Xen_StoragePoolManagementService_CreateResourcePool{
    Xen_StoragePoolManagementService_CreateResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_CreateResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_CreateResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_CreateResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_CreateResourcePool_Failed=4,
    Xen_StoragePoolManagementService_CreateResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_CreateResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_CreateResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    /*Xen_StoragePoolManagementService_CreateResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_CreateResourcePool_Method_Parameters_Checked___Job_Started=4096,
    Xen_StoragePoolManagementService_CreateResourcePool_Size_Not_Supported=4097,
    /*Xen_StoragePoolManagementService_CreateResourcePool_Method_Reserved=4098..32767,*/
    /*Xen_StoragePoolManagementService_CreateResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_CreateResourcePool;

typedef enum _Xen_StoragePoolManagementService_AddResourcesToResourcePool{
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Failed=4,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    /*Xen_StoragePoolManagementService_AddResourcesToResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Method_Parameters_Checked___Job_Started=4096,
    Xen_StoragePoolManagementService_AddResourcesToResourcePool_Size_Not_Supported=4097,
    /*Xen_StoragePoolManagementService_AddResourcesToResourcePool_Method_Reserved=4098..32767,*/
    /*Xen_StoragePoolManagementService_AddResourcesToResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_AddResourcesToResourcePool;

typedef enum _Xen_StoragePoolManagementService_DisconnectFromDiskImages{
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Not_Supported=1,
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Failed=2,
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Timeout=3,
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Invalid_Parameter=4,
    /*Xen_StoragePoolManagementService_DisconnectFromDiskImages_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_DisconnectFromDiskImages_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_StoragePoolManagementService_DisconnectFromDiskImages_Method_Reserved=4097..32767,*/
    /*Xen_StoragePoolManagementService_DisconnectFromDiskImages_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_DisconnectFromDiskImages;

typedef enum _Xen_StoragePoolManagementService_DeleteResourcePool{
    Xen_StoragePoolManagementService_DeleteResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_DeleteResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_DeleteResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_DeleteResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_DeleteResourcePool_Failed=4,
    Xen_StoragePoolManagementService_DeleteResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_DeleteResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_DeleteResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    /*Xen_StoragePoolManagementService_DeleteResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_DeleteResourcePool_Method_Parameters_Checked___Job_Started=4096,
    /*Xen_StoragePoolManagementService_DeleteResourcePool_Method_Reserved=4097..32767,*/
    /*Xen_StoragePoolManagementService_DeleteResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_DeleteResourcePool;

typedef enum _Xen_StoragePoolManagementService_CreateChildResourcePool{
    Xen_StoragePoolManagementService_CreateChildResourcePool_Job_Completed_with_No_Error=0,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Not_Supported=1,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Unknown=2,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Timeout=3,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Failed=4,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Invalid_Parameter=5,
    Xen_StoragePoolManagementService_CreateChildResourcePool_In_Use=6,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Incorrect_ResourceType_for_the_Pool=7,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Insufficient_Resources=8,
    /*Xen_StoragePoolManagementService_CreateChildResourcePool_DMTF_Reserved=..,*/
    Xen_StoragePoolManagementService_CreateChildResourcePool_Method_Parameters_Checked___Job_Started=4096,
    Xen_StoragePoolManagementService_CreateChildResourcePool_Size_Not_Supported=4097,
    /*Xen_StoragePoolManagementService_CreateChildResourcePool_Method_Reserved=4098..32767,*/
    /*Xen_StoragePoolManagementService_CreateChildResourcePool_Vendor_Specific=32768..65535,*/
}Xen_StoragePoolManagementService_CreateChildResourcePool;


#endif /*__XEN_STORAGEPOOLMANAGEMENTSERVICE_H__*/
